### ISSUE TITLE
Input Subject Code

### ISSUE THREAD

**Issue by khairulhafidz15** [afzafri/UiTM-Timetable-Generator#12]
I'd love to thank the developer of the system. Such a useful and innovative system. I'd say that the existing features are great, but it's still lacking in user experience. What I'm trying to say is that it would've been better if we could input our subject code rather than scroll through all the codes to find our subject. The existing scroll feature are great, don't remove it but adding an option for users to input code of the subject and give suggestions of the subjects while code are being keyed in would be a great feature and would be a great impact for pleasant user experience. And also, it would be even better if the autofetch feature could be use, but I'm not hoping for that to be improved anytime soon because it might be hard to prepare it. Anyway, thank you for reading this far and I hope you will take my humble suggestion into your consideration. Thank you :)

*I recently noticed that this feature has been there but only on desktop site and not on mobile phones.

**Comment by afzafri** [comment]
Hi Khairul, thank you for your kind words and support, really appreciate it.
 
First of all, yes indeed the search subject feature already available, but right now only for desktop site. This is due to the limitation of the search plugin used, which sadly only support desktop site. 
There are other better plugin, however the way this system was designed and develop initially makes it quite hard to implement this feature. We don't want to risk breaking other features during the implementation of this feature.

Through the released of iLearn v3, they decided to improve their site security by requiring users to log in again in order to access iLearn. This has prevents the system from able to gain access to the user's subjects list, hence why the feature is unusable now. Right now there are no plan in fixing this as it require more complex implementation with iLearn. We don't want to obtain the data illegally, and the data obtain are sensitive data which might put us into some serious risk.

If you know any developers who would like to improve this system, feels free to invite them. Right now all the developers of this project are busy with their daily commitment. Anyway, thank you again for your questions and suggestions :)

**Comment by shahril96** [comment]
I hate to say this, but....

The only way we can make this code scalable (and right too) is requiring a major rewrite to the backend system.

As far as I'm concerned, everybody which was involved with this project has graduated, and have their own daily job to handle. Quick history lesson: this was coded when we all are diploma student.

I'll try to look at this, but not anywhere soon.

**Comment by afzafri** [comment]
Subject searching is working now thanks to pull request #19
