### ISSUE TITLE
Is uitmtimetable.com expired?

### ISSUE THREAD

**Issue by ADIBzTER** [afzafri/UiTM-Timetable-Generator#22]
I checked on whois it says 19/3/2021 is the registry expiry date

**Comment by afzafri** [comment]
Hi @ADIBzTER , the website is no longer maintained by us, and yes seems like the domain name has expired. We are currently not looking into renewing it. The codes for the timetable also need to be updated due to some major changes by UiTM iCress system which breaks our Timetable core features.

We welcomed any contributors to update the project and host it again.

**Comment by ADIBzTER** [comment]
I believe they didn't touch the old iCress which this project uses. They released iCressV2 but on our registration system, they still use the old iCress. I've tried to generate my time table using this project on my pc and it has the same result as my friend who looks it up one by one on iCress.

Hope you can host this site. I believe it still works perfectly.
