### ISSUE TITLE
User customization and saving feature

### ISSUE THREAD

**Issue by sK11a** [afzafri/UiTM-Timetable-Generator#25]
I would recommend bringing back the customizable timetable feature and export to pdf button for the website. Also the dropdown for subjects would be good if there's a search bar included just for a quality of life purposes. Overall, the website does really help UiTM students to generate their timetable rather than wasting time searching through iCRESS. Thank you :)

**Comment by ADIBzTER** [comment]
Hi @sK11a. I believe you are using old version of this project that hosted on UiTM's official website. The latest website already implemented search bar for the subject. You can use [https://uitmtimetable.herokuapp.com](https://uitmtimetable.herokuapp.com) because [uitmtimetable.com](https://uitmtimetable.com) has expired.

**Comment by sK11a** [comment]
oouh thanks i love this

**Comment by afzafri** [comment]
Closing this issue. Export to PDF implemented in https://github.com/afzafri/UiTM-Timetable-Generator/commit/f50525e568d0348614d8a6ee0abd142a6ac67009
Latest website: https://uitmtimetable.skrin.xyz
