### ISSUE TITLE
No more free hosting on Heroku

### ISSUE THREAD

**Issue by ADIBzTER** [afzafri/UiTM-Timetable-Generator#40]
Received email from Heroku. They are discontinuing their free products. https://blog.heroku.com/next-chapter.

![Screenshot_20220826-010839_Yahoo Mail](https://user-images.githubusercontent.com/35218502/186729393-6e68f5c6-243a-4a16-96f4-eb6415b6ad3c.jpg)

Right now I'm using free tier to host the web app. After this, the cheapest dyno is $7 which expensive in my opinion. Any suggestion for this problem?

**Comment by alzhahir** [comment]
If you're not against it, you could use Oracle Cloud Infrastructure free tier and manually deploy the code to a VPS.

The free tier provides you two 1 OCPU and 1GB RAM AMD VPS and also a dynamic ARM server up to 4 OCPUs and 24GB RAM, although it is hard to get this since it's limited and many people uses them.

Furthermore, there's also Google Cloud free tier that also provides 1vCPU 1GB RAM VPS instance in the US.

If you're looking for something similar to Heroku, I think Glitch is a good alternative.

If you want to find more free services for devs, do visit [this page.](https://free-for.dev)

**Comment by ADIBzTER** [comment]
We are using cloud run for production server right now.
