### ISSUE TITLE
DID NOT SHOW THE GROUP OF THE COURSE

### ISSUE THREAD

**Issue by meiimeiii** [afzafri/UiTM-Timetable-Generator#41]
im from uitm kampus samarahan. when i clicked at the course (ASM655) it did not shows the group, instead showing the time, for example, MONDAY (10:00 a.m. - 12:00 p.m.) and then when i clicked, it shows "RangeError: Timetable scope should consist of (start, end) in whole hours from 0 to 23" and did not shows the timetable. please help me.

**Comment by tinananna** [comment]
sameee

**Comment by ajeeq** [comment]
For temporary solution and as alternative, can use this [UiTM Scheduler](https://play.google.com/store/apps/details?id=com.ajeeq.uitmscheduler) app from Play Store but currently it is in early access since there is lot of bug and still no function to generate timetable view. Just information regarding the course/subject.

![image](https://user-images.githubusercontent.com/60167498/193112932-e6889507-77e7-4e60-bef2-42213d234dd1.png)
![image](https://user-images.githubusercontent.com/60167498/193113023-5e6dacb1-19fe-4e43-bbc2-2fc7ff4b37d3.png)
